FORMAT: 1A

# Efimeral

Efimeral is an use-and-drop Linux boxes provider. This is the public API definition.

# Data Structures

## Error (object)
+ cause: stacktrace detail (string, required) - The technical error detail.
+ description: short description text (string, required) - Short description of the current error.

## BadRequestError (Error)
+ status: 400 (number, required) - The HTTP status value.

## NotFoundError (Error)
+ status: 404 (number, required) - The HTTP status value.

## NewSessionRequest (object)
+ distribution: ubuntu (string, required) - The distribution name to use.

## NewSessionResponse (object)
+ id: 63bbfea82b8880ed33cdb762aa11fab722a90a24 (string, required) - The ID of the new session recently created.

## ActiveSession (object)
+ id: 63bbfea82b8880ed33cdb762aa11fab722a90a24 (string, required) - The ID of the current session.
+ distribution: ubuntu (string, required) - The distribution name used.
+ tag: `17.04` (string, required) - The distribution's tag used.
+ created_at: `2018-12-08T12:00:00Z` (string, required) - The creation date of the session.
+ url: `http://localhost:9090/` (string, required) - The web console URL where the running container is available.

## DeletedSession (ActiveSession)
+ deleted_at: `2018-12-08T12:00:00Z` (string, required) - The elimination date of the session.

# Group Sessions

This group is about resources to manipulate user's sessions. 

## Sessions [/sessions]

### Create a new session [POST]

Creates a new session for the current web user. A new box will be created using the granted distribution ID. 

+ Request New ephemeral Linux box

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5c..._XiQiIkQ
            Accept: application/json

    + Attributes (NewSessionRequest)

+ Response 201 (application/json)

    + Headers

            Location: http://example.com/sessions/63bbfea82b8880ed33cdb762aa11fab722a90a24

    + Attributes (NewSessionResponse)

+ Response 400 (application/json)

    + Attributes (BadRequestError)

## Session [/sessions/{id}]

+ Parameters
    + id: 63bbfea82b8880ed33cdb762aa11fab722a90a24 (required, string) - ID of the Session to fetch metadata.

### Get session metadata [GET]

Returns a session metadata, if it exists.

+ Request Get session metadata

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5c..._XiQiIkQ
            Accept: application/json

+ Response 200 (application/json)
    + Attributes (ActiveSession)

+ Response 404 (application/json)
    + Attributes (NotFoundError)

### Delete existing session [DELETE]

Deletes indicated session ID from the system, if it exists.

+ Request Delete session

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5c..._XiQiIkQ
            Accept: application/json

+ Response 200 (application/json)
    + Attributes (DeletedSession)

+ Response 404 (application/json)
    + Attributes (NotFoundError)
