FORMAT: 1A

# Efimeral

Efimeral is a ephemeral Linux boxes provider. This is the public API
definition.

# Group Distributions

## Distribution Collection [/distributions]

### List available distributions [GET]

# Group Sessions

## Session Collection [/sessions]

### Create a new session [POST]
