version: '3'
services:
  web:
    image: "ariel17/efimeral:web"
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  api:
    image: "ariel17/efimeral:api"
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BASE_URL=http://localhost

