version: '3'
services:

  api:
    image: "ariel17/efimeral:api"
    ports:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BASE_URL=http://efimeral.com.ar

  docs:
    image: "ariel17/efimeral:docs"
    ports:
      - "80"

  web:
    image: "ariel17/efimeral:web"
    ports:
      - "80"
    depends_on:
      - api
      - docs

  nginx:
    image: "ariel17/efimeral:nginx"
    ports:
      - "80:80"
    depends_on:
      - api
      - docs
      - web
    links:
      - api
      - docs
      - web
